version: '3.8'

services:
  web:
    stdin_open: true
    build: .
    command: > 
      bash -c "
      python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:7000"
    restart: always
    volumes: 
      - .:/twitterapp
    container_name: twitterapp
    ports: 
      - 7000:7000

  db:
   image: postgres:9.4
   container_name: postgres
   tty: true
   restart: always
   volumes:
     - postgres:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - "5432:5432"


volumes:
  postgres:
