version: '3.8'

services:
  
  web_api:
   stdin_open: true
   container_name: twitter_api
   build: .
   command: python manage.py runserver 0.0.0.0:7000
   restart: always
   volumes: 
     - .:/apptwitter
   ports: 
     - 7000:7000

  db:
   image: postgres:9.4
   container_name: postgres
   tty: true
   restart: always
   volumes:
     - postgres:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=db_application
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - "5432:5432"
   depends_on:
     - web_api


volumes:
  postgres:
